_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 63b88d5f-1f0f-41d7-99bf-b2bc5bf860fe
name: 'SAML Test'
mail: vladimir.ivanov@usda.gov
slogan: ''
page:
  403: ''
  404: ''
  front: /saml_response
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
