_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  auditfiles: 0
  backup_migrate: 0
  better_exposed_filters: 0
  bg_image_formatter: 0
  blazy: 0
  block: 0
  block_content: 0
  block_content_machine_name: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_templates: 0
  ckeditor_templates_ui: 0
  color_field: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  conflict: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  easy_breadcrumb: 0
  editor: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_block: 0
  entity_reference_revisions: 0
  facets: 0
  facets_pretty_paths: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  govdelivery_signup: 0
  help: 0
  hierarchical_taxonomy_menu: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  insert_view: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_droppable: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  language: 0
  layout_builder: 0
  layout_builder_block: 0
  layout_builder_operation_link: 0
  layout_builder_restrictions: 0
  layout_builder_save_and_edit: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  link: 0
  linkit: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  media_parent_entity_link: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  openapi: 0
  openapi_jsonapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  openapi_ui_swagger: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  panels_ipe: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  rest: 0
  samlauth: 0
  schemata: 0
  schemata_json_schema: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  search_overrides: 0
  section_library: 0
  serialization: 0
  shortcut: 0
  simple_gmap: 0
  simple_search_form: 0
  slick: 0
  slick_entityreference: 0
  slick_extras: 0
  slick_ui: 0
  slick_views: 0
  smtp: 0
  sqlsrv: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  usda_ars_migrate: 0
  usda_scientific_discoveries_migrate: 0
  user: 0
  usfedgov_google_analytics: 0
  uswds_blb_configuration: 0
  uswds_ckeditor_integration: 0
  uswds_paragraph_components: 0
  views_block_filter_block: 0
  views_data_export: 0
  views_field_view: 0
  views_ui: 0
  viewsreference: 0
  extlink: 1
  pathauto: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  bartik: 0
  claro: 0
  uswds_base: 0
  usda_scient_discover_uswds: 0
profile: minimal
