_core:
  default_config_hash: 9rAU4Pku7eMBQxauQqAgjzlcicFZ2As6zEa6zvTlCB8
favicon:
  mimetype: image/vnd.microsoft.icon
  path: sites/scientific-discoveries/themes/custom/usda_scient_discover_uswds/uswds.ico
  url: ''
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: 'public://USDA-Logo.png'
  url: ''
  use_default: false
